from __future__ import annotations

from enum import Enum


INVALID_ATTESTATION = "INVALID_ATTESTATION"
KNOWN_AUTOMATION_FINGERPRINT = "KNOWN_AUTOMATION_FINGERPRINT"
IMPOSSIBLE_EVENT_SEQUENCE = "IMPOSSIBLE_EVENT_SEQUENCE"
CHALLENGE_FAILURE_DETERMINISTIC = "CHALLENGE_FAILURE_DETERMINISTIC"
TIMING_AUTOMATION_PATTERN = "TIMING_AUTOMATION_PATTERN"
CROSS_SESSION_CLUSTER_MATCH = "CROSS_SESSION_CLUSTER_MATCH"
EXCESSIVE_ROLE_DISAGREEMENT = "EXCESSIVE_ROLE_DISAGREEMENT"
HIGH_VALUE_TRANSACTION_ESCALATION = "HIGH_VALUE_TRANSACTION_ESCALATION"
POLICY_REQUIRES_STEP_UP = "POLICY_REQUIRES_STEP_UP"

ALL_REASON_CODES = {
    INVALID_ATTESTATION,
    KNOWN_AUTOMATION_FINGERPRINT,
    IMPOSSIBLE_EVENT_SEQUENCE,
    CHALLENGE_FAILURE_DETERMINISTIC,
    TIMING_AUTOMATION_PATTERN,
    CROSS_SESSION_CLUSTER_MATCH,
    EXCESSIVE_ROLE_DISAGREEMENT,
    HIGH_VALUE_TRANSACTION_ESCALATION,
    POLICY_REQUIRES_STEP_UP,
}


class ReasonCode(str, Enum):
    INVALID_ATTESTATION = INVALID_ATTESTATION
    KNOWN_AUTOMATION_FINGERPRINT = KNOWN_AUTOMATION_FINGERPRINT
    IMPOSSIBLE_EVENT_SEQUENCE = IMPOSSIBLE_EVENT_SEQUENCE
    CHALLENGE_FAILURE_DETERMINISTIC = CHALLENGE_FAILURE_DETERMINISTIC
    TIMING_AUTOMATION_PATTERN = TIMING_AUTOMATION_PATTERN
    CROSS_SESSION_CLUSTER_MATCH = CROSS_SESSION_CLUSTER_MATCH
    EXCESSIVE_ROLE_DISAGREEMENT = EXCESSIVE_ROLE_DISAGREEMENT
    HIGH_VALUE_TRANSACTION_ESCALATION = HIGH_VALUE_TRANSACTION_ESCALATION
    POLICY_REQUIRES_STEP_UP = POLICY_REQUIRES_STEP_UP
